### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by barrycxg** [zerchen/AlignSDF#13]
Thanks for sharing your work. I have a problem now. I can not download the training dataset from google cloud due to restrictions on the number of visits to web pages. Can you provide another download link of the training dataset?

**Comment by zerchen** [comment]
Hi,

Thanks for your attention.
Since the complete data is huge, I would like to know which part of data (ObMan or DexYCB) you need most urgently? I could help upload corresponding parts to BaiduDrive in coming days.

Best,
Zerui

**Comment by barrycxg** [comment]
I have downloaded the dataset through the bug of google cloud. I think it's great research work. I may further consult with you on the details of the work. Thanks for your reply and patience.
