### ISSUE TITLE
The difference between sdf_hand and sdf_hand_mini

### ISSUE THREAD

**Issue by barrycxg** [zerchen/AlignSDF#16]
I find the dataset you provided contains sdf_hand_mini and sdf_hand. I want to know the difference between sdf_hand and sdf_hand_mini.
Besides, when I run the command "CUDA_VISIBLE_DEVICES=0,1 bash dist_train.sh 2 6666 -e experiments/obman/30k_1e2d_mlp5.json --mano --obj_pose --point_size 9 --encode both --ocrw 0" to train the model, is the mini version of the dataset utilized?

**Comment by zerchen** [comment]
Hi,

The sdf_hand/obj_mini is the subset that I created for the student project, which is not used for producing numbers reported in the paper. If you want to get similar results shown in the paper, you need to use sdf_hand/obj files. Hope it clarifies your concerns.

Best,
Zerui

**Comment by barrycxg** [comment]
Thanks for your reply. Is the training example command you provided in the readme also based on sdf_hand/object ?

**Comment by zerchen** [comment]
Yes, exactly:)

**Comment by barrycxg** [comment]
Thanks for your reply.

**Comment by barrycxg** [comment]
I am sorry to disturb you. Can you provide the version number of your library in setup.py?

**Comment by shqmffl486** [comment]
How did you train using mini?
