### ISSUE TITLE
中国源

### ISSUE THREAD

**Issue by kuwan2e** [zerchen/AlignSDF#18]
google drive下载数据容易断
能否提供百度网盘的下载链接？
谢谢

**Comment by zerchen** [comment]
你好，

下周我会将相关数据在百度网盘上传一份。

**Comment by kuwan2e** [comment]
你好，请问度盘的数据上传有提上日程吗

**Comment by zerchen** [comment]
你好，

已经在上传中，数据量比较大且百度云上传速度较慢（600KB/s），需要一段时间。

**Comment by kuwan2e** [comment]
> 

感谢！

**Comment by zerchen** [comment]
百度网盘上传容易中断，所以把[数据](https://1drv.ms/f/s!Ak6n5pCF7XJ9vWw5kNz4D1SDxfEk?e=xZF6Ca)放在onedrive上了。数据已经大部分上传。数据的使用方式也可以参考这个[仓库](https://github.com/zerchen/gSDF)。
