### ISSUE TITLE
Preprocessed file are not generated in sdf_hand and sdf_obj but only in norm

### ISSUE THREAD

**Issue by karta2155802** [zerchen/AlignSDF#2]
I tried to preprocess one sample mesh to get the sdf values. After running `prep_obman.py`, I only get one npz file under **norm**, but nothing under **sdf_hand** and **sdf_obj**.
The terminal output error as below:
`OpenGL Error 500: GL_INVALID_ENUM: An unacceptable value is specified for an enumerated argument.
In: /usr/local/include/pangolin/gl/gl.hpp, line 205`
In [here](https://github.com/facebookresearch/DeepSDF/issues/35#issuecomment-568251730), people said they can still get the results with this error. Do you know how to solve this?
Thanks.

**Comment by zerchen** [comment]
Hi,

Previously, I also struggled with this issue, which probably suggests your PC lacks enough OpenGL support. If you work on a remote server, you need to execute "export PANGOLIN_WINDOW_URI=headless://".  Sometimes, it still does not work on a remote server. I suggest to work on a local ubuntu 20 machine with a GPU and enough OpenGL support.

**Comment by WeedsInML** [comment]
When I generate sdf_hand and sdf_obj, it's so time-consuming. Could you please provide your data?

**Comment by zerchen** [comment]
The processed training files are large (about 460G). I will try to find ways to upload them into the cloud.

**Comment by CODE-SUBMIT** [comment]
> Hi,
> 
> Previously, I also struggled with this issue, which probably suggests your PC lacks enough OpenGL support. If you work on a remote server, you need to execute "export PANGOLIN_WINDOW_URI=headless://". Sometimes, it still does not work on a remote server. I suggest to work on a local ubuntu 20 machine with a GPU and enough OpenGL support.

I only get norm folder, the error is terminate called after throwing an instance of 'pangolin::WindowExceptionNoKnownHandler, I check my ogengl, but there is nothing wrong.

How to solve it.

**Comment by zhangxinkang** [comment]
> Hi,
> 
> Previously, I also struggled with this issue, which probably suggests your PC lacks enough OpenGL support. If you work on a remote server, you need to execute "export PANGOLIN_WINDOW_URI=headless://". Sometimes, it still does not work on a remote server. I suggest to work on a local ubuntu 20 machine with a GPU and enough OpenGL support.

Hi, i get files in norm, sdf_hand and sdf_obj folders, but the number of files in them are different.
In my local computer, i got about 50000 files in norm folder, but just about 30000 files in sdf_hand and sdf_obj.
In our ubuntu server, the number of files in sdf_hand is 1/10 of the number of files in norm.

Do you know how to solve this?

**Comment by zerchen** [comment]
Sorry, I have no idea of this issue. However, I would put my processed data on the google cloud around end of November.

**Comment by zerchen** [comment]
Hi,

I have put my preprocessed data online. You could have a check at https://drive.google.com/drive/folders/1GoaA6vB6TwAAHmaobVo5GjRoCq2wT21R. Hope it helps resolve your issues.

Best,
Zerui

**Comment by EAST-J** [comment]
> Hi,
> 
> I have put my preprocessed data online. You could have a check at https://drive.google.com/drive/folders/1GoaA6vB6TwAAHmaobVo5GjRoCq2wT21R. Hope it helps resolve your issues.
> 
> Best, Zerui

Hi, Thanks for sharing. Could you also put preprocessed data for DexYCB?

**Comment by zerchen** [comment]
Yes, I will put the processed data for DexYCB next week.

**Comment by AkramSyed002** [comment]
@zerchen is there any way i can the script for the mesh_data of the DexYCB dataset? 
i have the processed sdf  files but its missing meshdata

thank you

**Comment by zerchen** [comment]
Thank you for your interests @AkramSyed002. I remember that the mesh data can be easily obtained by transforming the canonical hand and object meshes with corresponding hand and object pose annotations provided by the dexycb dataset.

**Comment by AkramSyed002** [comment]
@zerchen thank you for you quick response by any chance can you provide the script if available ?
thank you so much
