### ISSUE TITLE
How to evaluate like Table 4 in ECCV paper?

### ISSUE THREAD

**Issue by dqj5182** [zerchen/AlignSDF#23]
I just ran the code and it seems that the evaluation results of the code is in different metric that the Table 4 in ECCV 2022 paper. Could you give insight on how to evaluate like Table 4 in the ECCV 2022 paper?

**Comment by zerchen** [comment]
Hi,

Could you please provide more hints about which specific metric is quite different? I remember that the evaluation script in [gSDF repo](https://github.com/zerchen/gSDF) is more accurate. It also provides the implementation of alignsdf, and you could have a try on that one.
