### ISSUE TITLE
'obj_corners_3d' and 'obj_rest_corners_3d' in obman meta file

### ISSUE THREAD

**Issue by WeedsInML** [zerchen/AlignSDF#4]
Hello,
I tried to reproduce your work, and I found 'obj_corners_3d' and 'obj_rest_corners_3d' are not in obman meta file. How do you get them?

**Comment by WeedsInML** [comment]
And what does 'mesh_obj_rest' means?

**Comment by zerchen** [comment]
Hi,

'obj_corners_3d' and 'obj_rest_corners_3d' can be obtained from object meshes. You could use trimesh to obtain the tight 3D bounding box and corners. I think these two parameters is useless in this ECCV work, and you could ignore them. 'mesh_obj_rest' means the object mesh under its canonical pose (i.e., without applying the rigid pose).

Best,
Zerui

**Comment by zhangxinkang** [comment]
> 

Hi，i meet  the same problem, no obj_corners_3d and obj_rest_corners_3d in pkl file in the meta. But when i clean obj_corners_3d and obj_rest_corners_3d in the code, i found that they are needed to compute the center of obj, should i clean them to make the code available?

thank you

**Comment by zerchen** [comment]
Hi,

I have put my preprocessed data at https://drive.google.com/drive/folders/1GoaA6vB6TwAAHmaobVo5GjRoCq2wT21R, which could help resolve your issue.

Best,
Zerui
