### ISSUE TITLE
Missing test/mesh_obj_rest/ for obman test

### ISSUE THREAD

**Issue by EAST-J** [zerchen/AlignSDF#6]
Hi, thx for sharing such great work. When I tried to evaluate the model, it seems that some parts of the test data(test/mesh_obj_rest folder) are missing? After I modified it to /test/mesh_obj, it gives me warning like "WARNING:root:Cannot reconstruct mesh". Could you please tell me how to solve this?

**Comment by zerchen** [comment]
Thanks for your question. I have uploaded the folder 'test/mesh_obj_rest' to the google drive. You could have another try, but I think the issue "WARNING:root:Cannot reconstruct mesh" has little relevance to the missing folder.

**Comment by EAST-J** [comment]
Thank you for your prompt reply. I find the issue "WARNING:root:Cannot reconstruct mesh" relate to the 'skimage.measure.marching_cubes_lewiner' function. My version of skimage is 0.19.3, it seems that skimage has changed this. I solve this by downgrading it to version 0.16.2.

**Comment by zerchen** [comment]
You are welcome.
