### ISSUE TITLE
How to generate dexycb split names? 

### ISSUE THREAD

**Issue by WeedsInML** [zerchen/AlignSDF#7]
Hello,

I find in your code, you use "00141909" to index dexycb rgb images. But for the dataset, the image index is "20200820-subject-03/20200820_135323/932122062010/color_000000.jpg".  How do you create your own dexycb dataset. 

I follow official dexycb toolkit to run create_dataset.py and it shows the size of S1 split train is 407088, but in your code it's 148414.

**Comment by zerchen** [comment]
Hi,

You coud rename these samples by associating each sample with a unique id. 
Actually, I filter left-hand samples and some samples where hands and objects are away from each other, which results in reducing the number of samples from 407088 to 148414.

**Comment by zhangxinkang** [comment]
> Hi,
> 
> You coud rename these samples by associating each sample with a unique id. Actually, I filter left-hand samples and some samples where hands and objects are away from each other, which results in reducing the number of samples from 407088 to 148414.

Hi, zerui.
i used the script in issue8 but i got just about 120000 sample, is there any difference? thankyou .

Best,
Xinkang

**Comment by zerchen** [comment]
Hi,

Yes, you can use 's0' setup, which is the setting that I use in the paper.

Best,
Zerui

zhangxinkang ***@***.***> 于2023年1月5日周四 03:47写道：
